-- Phase 3: Initial Relational Schema for Enterprise AI Support Agent
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/peipnsmjaatousqjulbk/sql/new

-- 1. Users Table (RBAC Entity)
CREATE TABLE IF NOT EXISTS public.users (
    id VARCHAR(50) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(100),
    role VARCHAR(30) NOT NULL CHECK (role IN ('customer', 'support_agent', 'senior_agent', 'admin')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tickets Table
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    priority VARCHAR(20) NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    category VARCHAR(50) NOT NULL DEFAULT 'general' CHECK (category IN ('network', 'hardware', 'software', 'security', 'general')),
    created_by VARCHAR(50) NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    assigned_to VARCHAR(50) REFERENCES public.users(id) ON DELETE SET NULL,
    resolution_notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Audit Logs Table (For tracking privileged operations & LLM agent actions)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    action VARCHAR(100) NOT NULL,
    details JSONB DEFAULT '{}'::jsonb,
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Allow service_role to have full access (Bypass RLS for backend)
DROP POLICY IF EXISTS "Service role full access on users" ON public.users;
CREATE POLICY "Service role full access on users" ON public.users FOR ALL TO service_role USING (true);

DROP POLICY IF EXISTS "Service role full access on tickets" ON public.tickets;
CREATE POLICY "Service role full access on tickets" ON public.tickets FOR ALL TO service_role USING (true);

DROP POLICY IF EXISTS "Service role full access on audit_logs" ON public.audit_logs;
CREATE POLICY "Service role full access on audit_logs" ON public.audit_logs FOR ALL TO service_role USING (true);

-- Allow read access for authenticated API operations
DROP POLICY IF EXISTS "Allow read users" ON public.users;
CREATE POLICY "Allow read users" ON public.users FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow read tickets" ON public.tickets;
CREATE POLICY "Allow read tickets" ON public.tickets FOR SELECT USING (true);

-- 4. Seed Initial Users for RBAC Testing
INSERT INTO public.users (id, email, full_name, role) VALUES
    ('user_01', 'customer1@enterprise.local', 'Alice Customer', 'customer'),
    ('agent_01', 'support1@enterprise.local', 'Bob Support', 'support_agent'),
    ('senior_01', 'senior1@enterprise.local', 'Charlie Senior', 'senior_agent'),
    ('admin_01', 'admin1@enterprise.local', 'David Admin', 'admin')
ON CONFLICT (id) DO UPDATE 
SET email = EXCLUDED.email, full_name = EXCLUDED.full_name, role = EXCLUDED.role;

-- 5. Seed Initial Sample Tickets for user_01
INSERT INTO public.tickets (title, description, status, priority, category, created_by, assigned_to) VALUES
    ('Laptop docking station issue', 'Second external monitor flickers intermittently when connected via USB-C dock.', 'in_progress', 'high', 'hardware', 'user_01', 'agent_01'),
    ('Software license renewal for IDE', 'Requesting renewal for JetBrains license key expiring next week.', 'resolved', 'low', 'software', 'user_01', 'agent_01'),
    ('VPN configuration on macOS', 'Need setup assistance for WireGuard corporate VPN profile on MacBook Pro.', 'open', 'medium', 'network', 'user_01', NULL)
ON CONFLICT DO NOTHING;
