from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from app.schemas.auth_schema import UserRole
from app.schemas.intent_schema import IntentType


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=4000, description="The user message to process")
    conversation_id: Optional[str] = Field(default=None, description="Optional thread or conversation ID")


class ExecutionStep(BaseModel):
    step_name: str
    status: str
    details: Optional[Dict[str, Any]] = None


class ChatResponse(BaseModel):
    response: str = Field(..., description="The final response generated by the agent")
    intent: IntentType = Field(..., description="The detected intent")
    confidence: float = Field(..., description="Classification confidence")
    user_role: UserRole = Field(..., description="The role of the requesting user")
    is_authorized: bool = Field(..., description="Whether the user had permission for this intent")
    conversation_id: Optional[str] = Field(default=None)
    execution_trace: Optional[List[ExecutionStep]] = Field(
        default_factory=list,
        description="List of nodes executed in the graph"
    )
