from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from app.schemas.auth_schema import UserRole
from app.schemas.intent_schema import IntentType


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=4000, description="The user message to process")
    conversation_id: Optional[str] = Field(default=None, description="Optional thread or conversation ID")
    thread_id: Optional[str] = Field(default=None, description="LangGraph thread ID (synonym for conversation_id)")


class ExecutionStep(BaseModel):
    step_name: str
    status: str
    details: Optional[Dict[str, Any]] = None


class ChatResponse(BaseModel):
    response: str = Field(..., description="The final response generated by the agent")
    intent: IntentType = Field(..., description="The detected intent")
    confidence: float = Field(..., description="Classification confidence")
    user_role: UserRole = Field(..., description="The role of the requesting user")
    is_authorized: bool = Field(..., description="Whether the user had permission for this intent")
    conversation_id: Optional[str] = Field(default=None)
    thread_id: Optional[str] = Field(default=None, description="LangGraph thread identifier")
    sources: Optional[List[str]] = Field(
        default_factory=list,
        description="Knowledge base sources and section references"
    )
    execution_trace: Optional[List[ExecutionStep]] = Field(
        default_factory=list,
        description="List of nodes executed in the graph"
    )
    # Phase 4: External Search & Human-in-the-Loop fields
    external_results: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="External search results from Tavily or vendor status"
    )
    approval_required: bool = Field(
        default=False,
        description="Whether this request is paused waiting for human supervisor approval"
    )
    approval_status: Optional[str] = Field(
        default=None,
        description="Status of approval: PENDING, APPROVED, or REJECTED"
    )
    approval_details: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Metadata details of the pending approval action"
    )

    # Phase 9: Vector Semantic Caching fields
    cached: bool = Field(
        default=False,
        description="Whether the response was served from vector semantic cache"
    )
    cache_score: Optional[float] = Field(
        default=None,
        description="Cosine similarity score for the cached match"
    )


class ApprovalDecisionRequest(BaseModel):
    approved: bool = Field(..., description="True to approve and execute, False to reject")
    reviewer_notes: Optional[str] = Field(
        default="",
        description="Optional supervisor justification or notes"
    )

